name: Run Tests for Nickoscope

on: [push, pull_request]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Action V2
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip3 install cookiecutter==1.7.2

      - name: Run flake8
        run: |
          flake8
